meta_name: "Sting | Get Strong or Get Stung"
meta_title: "The app that helps you reach your fitness goals"
meta_description: "Sting is a fitness app that helps you reach your goal. You bet money and lose it when you don't reach your goals."
meta_image: "banner_stingy.png" # should exist in `app/assets/images/`
